cabal-version: 3.0
name:
  miso-tagsoup
version:
  0.1.0.0
synopsis:
  Parse raw HTML / SVG into miso View
description:
  HTML / SVG parser that translates into View
bug-reports:
  https://github.com/dmjio/miso-tagsoup/issues
license:
  BSD-3-Clause
license-file:
  LICENSE
author:
  David Johnson
maintainer:
  code@dmj.io
copyright:
  (c) David Johnson 2026
category:
  Web
build-type:
  Simple
extra-source-files:
  README.md

common cpp
  if impl(ghcjs) || arch(javascript)
    cpp-options:
      -DGHCJS_BOTH
  if impl(ghcjs)
    cpp-options:
      -DGHCJS_OLD
  elif arch(javascript)
    cpp-options:
      -DGHCJS_NEW
  elif arch(wasm32)
    cpp-options:
      -DWASM
  else
    cpp-options:
      -DVANILLA

library
  import:
    cpp
  default-language:
    Haskell2010
  ghc-options:
    -Wall
  hs-source-dirs:
    src
  exposed-modules:
    Miso.Html.Parse
  build-depends:
    base < 5,
    miso >= 1.14 && < 1.15,
    tagsoup < 0.15

source-repository head
   type: git
   location: https://github.com/dmjio/miso-tagsoup.git
